# Generated by Django 5.0.6 on 2024-07-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OAuthQQUser',
        ),
    ]
